### ISSUE TITLE
Low CPU usage

### ISSUE THREAD

**Issue by szx0112** [classner/pymp#12]
Hi, the pymp looks great on my previous applications. Recently, I try to implement it on a big project. I make the pymp serves the uppermost loop like below

```
num = 10
params_pymp = pymp.shared.list(params)
with pymp.Parallel(10) as p:
                for j in p.range(num):
                            my_function(params_pymp[j])
```

The 'my_function' is a heavy processing function that contains a lot of inner for loops and matrix computations. 

When I just use the pure sequential for loop, the 10 iterations takes about 30 mins with a single core at 100% usage rate.
However, after I implement the pymp with 5~10 cores, it still takes around 35 mins or longer while each core has only 20-30% CPU usage rate.

I am confused about the result. I avoid to call pymp as the inner loop as it will become super slow when the 2nd for iteration starts, like below.

```
for i in range(10):
    with pymp.Parallel(10) as p:
              my_subFuntion()
```

I guess this is because the pymp have to allocate the memory at each iteration. Is there anything I missed? Or any other ways so I can increase the cpu usage rates? 

Any comment is appreciated. Thanks

**Comment by classner** [comment]
Hi @szx0112 ,

somehow I missed out on this issue, sorry! Have you been able to solve it?

pymp does not have any overhead w.r.t. memory allocation per iteration. Things that may cause this behavior are for example heavily memory-bound processes. Another reason can be large parameter objects that go through the loop function you iterate over (if you're using p.range for example, but this does not seem to be the case in the code you provided), because they're serialized to be transferred between processes.

In any case, let me know how it went for you.
