### ISSUE TITLE
Unable to debug on Pycharm using Pymp

### ISSUE THREAD

**Issue by pyetrotype** [classner/pymp#17]
Version:pymp-pypi==0.4.2
OS: NAME="Pop!_OS", VERSION="20.04 LTS" 
Python version: 3.7.7
Pycharm 2020.2

Usage:
```
`import pymp`

with pymp.Parallel(num_jobs) as p:
    for entity in tqdm(job_entities_list):
      .....

```

Problem: Execution performs with no errors, but I'm not able to inspect variables in debug mode using Pycharm. 
               It keeps indefinitely giving: "Collecting data".
               For my surprise, this problem happens in a context outside the multithreading block, for my whole application.

I made sure the problem is related to pymp because I didn't have this before. 
In fact, the simple act of importing the library, without using it, is enough to trigger the problem.

**Comment by classner** [comment]
Hi @pyetrotype !

I am not a PyCharm user, but I think I have a pretty clear idea about what's happening here. On a high level, I assume PyCharm is attaching to the Python process (which is usually single threaded) to try to read the variable values. As soon as pymp is used and active, the assumption that there's only a single process doesn't hold any more, and then probably things start to go sideways somewhere.

For debugging, I'd anyways recommend to set `if_=False` in the `Parallel` section constructor - in that case everything should work as expected.

**Comment by pyetrotype** [comment]
Hi @classner ,

Thank you for your reply.

I tried to isolate the problem and I have a guess some context is left behind after leaving the parallel section.

```
import pymp
    with pymp.Parallel(num_jobs) as mp:
        ...
del pymp
```
As I'm not debugging the functionality inside the Parallel block, I set a breakpoint after the `del pymp` stmt.
In this case I'm also getting the "Collecting data" behaviour.

I also tried the if_=False, but it turns off the parallelization. 
This can be helpful to debug inside the parallel section, this is not the case.

**Comment by classner** [comment]
> I have a guess some context is left behind after leaving the parallel section

Sure, the `mp` object in this case, though this does a proper cleanup on exit of the section. If you want to delete anything explicitly, you'd have to `del mp` in the above code. However, this will not (or better: should not) change anything in this case. (As a sidenote: by doing `del pymp` you just remove the pointer to the imported module from the local namespace. The pymp module remains imported for the current process.)

I do not know exactly how PyCharm tries to do introspection, hence I can not really give guidance on how to change what is happening here. The forking that happens when entering the pymp section might screw that up, but again, I can't say more without knowing exactly how that works.

Indeed, `if_=False` turns off the parallelization, which should allow you to use the PyCharm introspection within and outside of the relevant region (which is what you wanted, right?). Within the parallel region, PyCharm introspection will not work anyways, because the objects created there might belong to other processes. Other debugging, for example using pdb, also doesn't work there because of how the console is handled. However, if you *must* use the parallel processing in the first place and then want to continue debugging, I highly recommend pdb++, which should work great there.

**Comment by classner** [comment]
Hi @pyetrotype ,

any updates on this?
