### ISSUE TITLE
Not working under Python 3.5.5?

### ISSUE THREAD

**Issue by nnccoo** [classner/pymp#5]
I am trying to get pymp working with the following code:
> from __future__ import print_function
> import numpy as np
> import pymp
> 
> ex_array = pymp.shared.array((100,), dtype='uint8')
> with pymp.Parallel(4) as p:
>     for index in p.range(0, 100):
>         ex_array[index] = 1
>         # The parallel print function takes care of asynchronous output.
>         p.print('Yay! {} done!'.format(index))

It seems to me, as if python 3.5.x is not supported, when I compile only the console is busy but nothing happens?
I am using Python 3.5.5 |Anaconda, Inc.| (default, Apr  7 2018, 04:52:34) [MSC v.1900 64 bit (AMD64)]

**Comment by classner** [comment]
I assume from the Python version line that you're on Windows (MSC v.1900 64 bit (AMD64)), is that correct? Unfortunately, pymp relies on `fork` support from the operating system for efficiency and Windows does not offer that. That's why pymp doesn't run under Windows (see doc).

However, just leaving the console busy is not a good way to communicate that to users. I was expecting `os.fork` to fail with an exception instead of just idling. If you confirm that that's the reason, I'll add a proper check and error message.

**Comment by nnccoo** [comment]
Classner, thank you very much for the fast reply. As a python newbie I feel dumb not realising it does not run under windows.

You are right, that when running pymp under windows it is only idling. Nothing happens.
Thank you again. I will try to find a working solution for me. Cheers

**Comment by classner** [comment]
I just added a proper platform check with an Exception to provide more informative information to users. It would be great if you could check that this properly fails now on Windows. :) Then I'll close this issue.

The updated version is pushed to pypi, so doing a `pip install --upgrade pymp-pypi` should give you the latest version.

**Comment by classner** [comment]
Hi @nnccoo  ,

I would love to clean up the issues for this project. Can you confirm that this produces now a reasonable error message on Windows? If there's no response, I'm going to close this issue in the next days.

Thanks!
