### ISSUE TITLE
Ctrl + C stopping does not work

### ISSUE THREAD

**Issue by zhangmozhe** [classner/pymp#6]
The work is really nice. The problem is how to stop the code during running. It seems that Ctrl+C does not work and the processes cannot be stopped.

**Comment by classner** [comment]
Hi @zhangmozhe ,

this is due to the multi-threading and an inherent problem that's not (easily) solvable. You an try Ctrl+\, but some processes may continue to run. You can always use `if_=False` for debugging to finalize your code and then only remove that for deployment to minimize the hassle with this.
